### ISSUE TITLE
percentage based width + window resizing

### ISSUE THREAD

**Issue by leonardodino** [antw/quinn#6]
before complaining, I wanted to thank you, its a marvellous plugin, and really well designed. But, i cant see a method for redrawing, I would be ok with dealing with the resize event, as I'm already wrapping quinn into another module 

before resize:
![screen shot 2015-07-01 at 10 24 17](https://cloud.githubusercontent.com/assets/8649362/8455485/5d86150c-1fdb-11e5-8304-1779d872a3f9.png)

after:
![screen shot 2015-07-01 at 10 24 54](https://cloud.githubusercontent.com/assets/8649362/8455498/71cba4a0-1fdb-11e5-8116-7122b7976d27.png)

**Comment by antw** [comment]
Hi, thanks for your feedback.

Can you please try out [the version on the resize-event branch](https://raw.githubusercontent.com/antw/quinn/resize-event/jquery.quinn.js) and see if that fixes your problem? You'll have to tell Quinn that it has been resized by running:

```js
$('.your-slider').data('quinn').trigger('resize');
```

**Comment by leonardodino** [comment]
wow, that was fast (:

thanks, I'll test today. keep the good work
